### ISSUE TITLE
Create Nonsymbolic Comparison

### ISSUE THREAD

**Issue by cbattista** [StanfordCosyne/screener#1]
use Run.js as a template 

need to incorporate circles.js and a new circle drawing function

do this in a new branch

you can launch your web server using "python -m SimpleHTTPServer 8000"

**Comment by cbattista** [comment]
forgot to mention - if you look at index.html in this repo, you'll see how the website calls the necessary JS files - here is where it knows that 'Run.js' is what you want to invoke - https://github.com/StanfordCosyne/screener/blob/master/index.html#L31

**Comment by theochiu** [comment]
Where in the run.js file, should I insert my phaser code for the circles? I'm not sure how my function's supposed to play with the scoring, difficulty modifiers, or random selection.

**Comment by cbattista** [comment]
The drawing part goes right here -
https://github.com/StanfordCosyne/screener/blob/master/Run.js#L105.  The
program already knows how many dots should be showing up (this is
determined in the .generate function).  So at line 105, that's where the
actual drawing happens as the numbers are being shown to the user.  Right
now there's no 'i' or 'c' stuff being determined yet, so you'll have to add
that yourself in generate -
https://github.com/StanfordCosyne/screener/blob/master/Run.js#L153

Lastly, in Run.js, the sprites n1 and n2 are text objects, and they show
the number on the left (n1) and right (n2) - they get created here -
https://github.com/StanfordCosyne/screener/blob/master/Run.js#L42.  This
would be the place you initialize your graphics objects (and then you'd do
the actual drawing on line 105).
