### ISSUE TITLE
Clear canvas 

### ISSUE THREAD

**Issue by theochiu** [StanfordCosyne/screener#2]
Canvas doesn't clear dots so the dots from the last problem are still up, making game confusing and impossible to win.

**Comment by cbattista** [comment]
If there's no 'clear' function, an easy fix could be to draw a big
rectangle that's the same color as the background...

-C

**Comment by theochiu** [comment]
phaser has a destroy() command, but it seems to wipe everything out, so it clears the screen, but its pretty permanent so the circles don't come back for the next screen. If I generate a rectangle will it know to layer the previous circles underneath, and the future circles on top. Also will the frame rate go down since objects are being added constantly and nothing is removed?

**Comment by cbattista** [comment]
1 - Stuff will be drawn in the order you ask it to draw.  So, if you draw a
rectangle during the 'ISI' and/or 'fixation' phases, it will cover them
up...and then they'll appear again the next time the 'stimulus' phase is
entered...

2 - Frame rate should be fine - the graphics object is just a single entity
that has a set of pixels that can be manipulated.  Drawing
circles/recantangles just changes the RGB values of the pixels, so it
doesn't add to the sprite/object count at all.  Good for you for thinking
of that, though.
